name    'ginja-puppet_stack'
version '0.0.1'
source 'git://github.com/Ginja/puppet_stack.git'
author 'rshott'
license 'Apache License, Version 2.0'
summary 'Puppet module for managing foreman, smart-proxy, and a puppet master'
description 'Module for installing and managing Puppet, The Foreman, & smart-proxy'
project_page 'https://github.com/Ginja/puppet_stack'

dependency 'puppetlabs/apache', '>=1.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/postgresql', '>= 3.1.0 <4.0.0'
dependency 'maestrodev-rvm', '1.5.x'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
